### ISSUE TITLE
Dependencies problems.

### ISSUE THREAD

**Issue by krNeko9t** [GravisZro/ASIP#1]
Dear author, first of all thanks for your magnificent work and sharing spirit! I met some problems while building your project, and I think it's dependencies' version poblem. Will you be more specific about all the Third Party Libraries version and IDE version? And it would be great if you update this project! Thanks a lot!

**Comment by GravisZro** [comment]
Oh, I just uploaded the contents of a zip from https://team.inria.fr/titane/software/ (the Asip (Approximating Shapes in Images with Polygons, CVPR2020) link).  I did this because I couldn't find it in any repo anywhere.  I'm not the the person who wrote the software and honestly, I haven't even built the thing yet so I can't provide additional information.  I agree it's a fine piece of software and would like to improve it.  Life has been rather busy lately (personally renovating my house!), so I completely forgot about this project.

I want to work on this project but no promises.  I'll add info about what versions I've tried when I build it.

**Comment by krNeko9t** [comment]
HAHAHA. Thanks any way. And I just built it with the help of vcpkg which can only use the latest version of package, so it was a painful experience. And I end up with only built it in release mode, and the application crashes very often. So maybe proper version is necessary, and ask the author is a short cut. So good luck! And by the way, hope your decoration goes well!
